// <auto-generated />
namespace Biosite.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class Biositev3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Biositev3));
        
        string IMigrationMetadata.Id
        {
            get { return "202002091648094_Biosite-v3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
