// <auto-generated />
namespace Biosite.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class biosite_15032020_0101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(biosite_15032020_0101));
        
        string IMigrationMetadata.Id
        {
            get { return "202003150401489_biosite_15032020_0101"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
